/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4vabegwct5ggrkdrc4qh2crava.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-blnnwr2elfgi5ommr74kngc7j4",
    "aws_cognito_identity_pool_id": "us-east-1:5fecb0ca-678f-4db6-a41e-5049c5896931",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9aZ5p6RHD",
    "aws_user_pools_web_client_id": "14tqf19n7cgt2elf52mnpfaum",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "amplifyapp-20230828164107-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1xtk587iuu46l.cloudfront.net"
};


export default awsmobile;
